# Dale un nombre a tu proyecto (sin espacios ni guiones)
name: 'animum_dwh'
version: '1.0.0'
config-version: 2

# Perfil de conexión (dbt Cloud lo gestiona, pero es bueno tenerlo)
profile: 'default'

# Aquí va la configuración del paquete de Google Ads que te di antes
models:
  google_ads:
    # El nombre de tu proyecto en GCP
    +database: "animum-dev-datawarehouse"  
    
    # !!! RECUERDA CAMBIAR ESTO !!!
    # El dataset donde están tus tablas p_...
    +schema: "gads_01raw_01"           
    
    # Le dice al paquete que use las tablas de DTS
    +using_data_transfer_service: true